/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import entidade.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import persistencia.HibernateUtil;

/**
 *
 * @author
 */
public final class Produtos extends javax.swing.JInternalFrame {

    Produto prod = new Produto();
    private List<Produto> listaProdutos = new ArrayList<>();

    /**
     * Creates new form Produtos
     */
    public Produtos() {
        initComponents();
        montaTabela();
        validaCampos("inicio");

    }

    public void validaCampos(String operacao) {

        if (operacao == "inicio") {
            prodNome.setEnabled(false);
            prodDescricao.setEnabled(false);
            prodQuantidade.setEnabled(false);
            prodValor.setEnabled(false);
            prodExcluir.setEnabled(false);
            prodSalvar.setEnabled(false);
            prodCancelar.setEnabled(false);
            prodSair.setEnabled(true);
            prodNovo.setEnabled(true);
            prodAlterar.setEnabled(false);
        } else if (operacao == "novo") {
            prodNome.setEnabled(true);
            prodDescricao.setEnabled(true);
            prodValor.setEnabled(true);
            prodQuantidade.setEnabled(true);
            prodAlterar.setEnabled(false);
            prodExcluir.setEnabled(true);
            prodSalvar.setEnabled(true);
            prodCancelar.setEnabled(true);
        } else if (operacao == "selecionado") {

            prodNome.setEnabled(false);
            prodDescricao.setEnabled(false);
            prodValor.setEnabled(false);
            prodQuantidade.setEnabled(false);
            prodNovo.setEnabled(true);
            prodAlterar.setEnabled(true);
            prodExcluir.setEnabled(true);
            prodSalvar.setEnabled(false);
            prodCancelar.setEnabled(false);
            prodSair.setEnabled(true);
        }

    }

    public void montaTabela() {

        listaProdutos = HibernateUtil.getSession().createQuery("from Produto").list();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("Quantidade estoque");
        modelo.addColumn("Valor");

        for (Produto produto : listaProdutos) {
            modelo.addRow(new Object[]{produto.getNomeProd(), produto.getQuantProd(), produto.getValorProd().replace(".", ",")});
        }

        tabelaProd.setModel(modelo);

    }

    public void limparCampos() {
        prodNome.setText("");
        prodDescricao.setText("");
        prodValor.setText("");
        prodQuantidade.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prodNome = new javax.swing.JTextField();
        prodDescricao = new javax.swing.JTextField();
        prodValor = new javax.swing.JTextField();
        prodQuantidade = new javax.swing.JTextField();
        prodNovo = new javax.swing.JButton();
        prodAlterar = new javax.swing.JButton();
        prodExcluir = new javax.swing.JButton();
        prodSalvar = new javax.swing.JButton();
        prodCancelar = new javax.swing.JButton();
        prodSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProd = new javax.swing.JTable();

        jTextField5.setText("jTextField5");

        jButton7.setText("jButton7");

        setClosable(true);

        jLabel1.setText("Nome:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Quantidade:");

        prodNovo.setText("Novo");
        prodNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodNovoActionPerformed(evt);
            }
        });

        prodAlterar.setText("Alterar");
        prodAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodAlterarActionPerformed(evt);
            }
        });

        prodExcluir.setText("Excluir");
        prodExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodExcluirActionPerformed(evt);
            }
        });

        prodSalvar.setText("Salvar");
        prodSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSalvarActionPerformed(evt);
            }
        });

        prodCancelar.setText("Cancelar");
        prodCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodCancelarActionPerformed(evt);
            }
        });

        prodSair.setText("Sair");
        prodSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSairActionPerformed(evt);
            }
        });

        tabelaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodNome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodValor, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prodNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(prodNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodNovo)
                    .addComponent(prodAlterar)
                    .addComponent(prodExcluir)
                    .addComponent(prodSalvar)
                    .addComponent(prodCancelar)
                    .addComponent(prodSair))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSalvarActionPerformed
        // TODO add your handling code here:
        prod.setNomeProd(prodNome.getText());
        prod.setDescProd(prodDescricao.getText());
        prod.setQuantProd(prodQuantidade.getText());
        prod.setValorProd(prodValor.getText().replace(",", "."));

        HibernateUtil.beginTransaction();
        HibernateUtil.getSession().merge(prod);
        HibernateUtil.commitTransaction();
        HibernateUtil.closeSession();

        prod = new Produto();
        limparCampos();
        montaTabela();
        validaCampos("inicio");
    }//GEN-LAST:event_prodSalvarActionPerformed

    private void prodNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodNovoActionPerformed
        // TODO add your handling code here:
        limparCampos();
        validaCampos("novo");
    }//GEN-LAST:event_prodNovoActionPerformed

    private void prodAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodAlterarActionPerformed
        // TODO add your handling code here:
        validaCampos("novo");
    }//GEN-LAST:event_prodAlterarActionPerformed

    private void prodExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodExcluirActionPerformed
        // TODO add your handling code here:
        HibernateUtil.beginTransaction();
        HibernateUtil.getSession().delete(prod);
        HibernateUtil.commitTransaction();
        HibernateUtil.closeSession();

        limparCampos();
        montaTabela();
        validaCampos("inicio");
    }//GEN-LAST:event_prodExcluirActionPerformed

    private void prodCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        validaCampos("inicio");
    }//GEN-LAST:event_prodCancelarActionPerformed

    private void prodSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_prodSairActionPerformed

    private void tabelaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdMouseClicked
        // TODO add your handling code here:
        prod = listaProdutos.get(tabelaProd.getSelectedRow());
        prodNome.setText(prod.getNomeProd().toString());
        prodQuantidade.setText(prod.getQuantProd());
        prodValor.setText(prod.getValorProd());
        prodDescricao.setText(prod.getDescProd());

        validaCampos("selecionado");
    }//GEN-LAST:event_tabelaProdMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton prodAlterar;
    private javax.swing.JButton prodCancelar;
    private javax.swing.JTextField prodDescricao;
    private javax.swing.JButton prodExcluir;
    private javax.swing.JTextField prodNome;
    private javax.swing.JButton prodNovo;
    private javax.swing.JTextField prodQuantidade;
    private javax.swing.JButton prodSair;
    private javax.swing.JButton prodSalvar;
    private javax.swing.JTextField prodValor;
    private javax.swing.JTable tabelaProd;
    // End of variables declaration//GEN-END:variables
}
